# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deepdata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobuf_test.common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='deepdata.proto',
  package='dg.model',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x64\x65\x65pdata.proto\x12\x08\x64g.model\x1a\x0c\x63ommon.proto\"i\n\nGenericObj\x12\"\n\x07ObjType\x18\x01 \x01(\x0e\x32\x11.dg.model.ObjType\x12&\n\x07\x46mtType\x18\x02 \x01(\x0e\x32\x15.dg.model.DataFmtType\x12\x0f\n\x07\x42inData\x18\x03 \x01(\x0c*w\n\x0c\x43utboardType\x12\x19\n\x15\x43UTBOARD_TYPE_UNKNOWN\x10\x00\x12\x19\n\x15\x43UTBOARD_TYPE_VEHICLE\x10\x01\x12\x18\n\x14\x43UTBOARD_TYPE_SYMBOL\x10\x02\x12\x17\n\x13\x43UTBOARD_TYPE_PLATE\x10\x03\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_CUTBOARDTYPE = _descriptor.EnumDescriptor(
  name='CutboardType',
  full_name='dg.model.CutboardType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CUTBOARD_TYPE_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUTBOARD_TYPE_VEHICLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUTBOARD_TYPE_SYMBOL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUTBOARD_TYPE_PLATE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=149,
  serialized_end=268,
)
_sym_db.RegisterEnumDescriptor(_CUTBOARDTYPE)

CutboardType = enum_type_wrapper.EnumTypeWrapper(_CUTBOARDTYPE)
CUTBOARD_TYPE_UNKNOWN = 0
CUTBOARD_TYPE_VEHICLE = 1
CUTBOARD_TYPE_SYMBOL = 2
CUTBOARD_TYPE_PLATE = 3



_GENERICOBJ = _descriptor.Descriptor(
  name='GenericObj',
  full_name='dg.model.GenericObj',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ObjType', full_name='dg.model.GenericObj.ObjType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FmtType', full_name='dg.model.GenericObj.FmtType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BinData', full_name='dg.model.GenericObj.BinData', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=147,
)

_GENERICOBJ.fields_by_name['ObjType'].enum_type = common__pb2._OBJTYPE
_GENERICOBJ.fields_by_name['FmtType'].enum_type = common__pb2._DATAFMTTYPE
DESCRIPTOR.message_types_by_name['GenericObj'] = _GENERICOBJ
DESCRIPTOR.enum_types_by_name['CutboardType'] = _CUTBOARDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenericObj = _reflection.GeneratedProtocolMessageType('GenericObj', (_message.Message,), dict(
  DESCRIPTOR = _GENERICOBJ,
  __module__ = 'deepdata_pb2'
  # @@protoc_insertion_point(class_scope:dg.model.GenericObj)
  ))
_sym_db.RegisterMessage(GenericObj)


# @@protoc_insertion_point(module_scope)
