# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: localcommon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='localcommon.proto',
  package='dg.model',
  syntax='proto3',
  serialized_pb=_b('\n\x11localcommon.proto\x12\x08\x64g.model\")\n\x04Time\x12\x0f\n\x07Seconds\x18\x01 \x01(\x03\x12\x10\n\x08NanoSecs\x18\x02 \x01(\x03\",\n\x0bMatrixError\x12\x0c\n\x04\x43ode\x18\x01 \x01(\x05\x12\x0f\n\x07Message\x18\x02 \x01(\t*`\n\rRecognizeType\x12\x14\n\x10REC_TYPE_INVALID\x10\x00\x12\x14\n\x10REC_TYPE_VEHICLE\x10\x01\x12\x11\n\rREC_TYPE_FACE\x10\x02\x12\x10\n\x0cREC_TYPE_ALL\x10\x03*L\n\x08RankType\x12\x15\n\x11RANK_TYPE_DEFAULT\x10\x00\x12\x15\n\x11RANK_TYPE_VEHICLE\x10\x01\x12\x12\n\x0eRANK_TYPE_FACE\x10\x02*\x98\x06\n\x12RecognizeFunctions\x12\x13\n\x0fRECFUNC_INVALID\x10\x00\x12\x1a\n\x16RECFUNC_VEHICLE_DETECT\x10\x64\x12\x17\n\x13RECFUNC_MOTOR_STYLE\x10\x65\x12\x17\n\x13RECFUNC_MOTOR_COLOR\x10\x66\x12\x18\n\x14RECFUNC_MOTOR_MARKER\x10g\x12\x17\n\x13RECFUNC_MOTOR_PLATE\x10h\x12\x19\n\x15RECFUNC_MOTOR_FEATURE\x10i\x12\x1d\n\x19RECFUNC_MOTOR_DRIVER_BELT\x10j\x12\x1e\n\x1aRECFUNC_MOTOR_DRIVER_PHONE\x10k\x12\x1f\n\x1bRECFUNC_MOTOR_CODRIVER_BELT\x10l\x12+\n\'RECFUNC_MOTOR_DANGEROUS_ARTICLES_DETECT\x10m\x12(\n$RECFUNC_MOTOR_HEAVY_POLLUTION_DETECT\x10n\x12\x1d\n\x19RECFUNC_MOTOR_MUCK_DETECT\x10o\x12\"\n\x1eRECFUNC_MOTOR_FACECOVER_DETECT\x10p\x12\x18\n\x13RECFUNC_FACE_DETECT\x10\xc8\x01\x12\x1b\n\x16RECFUNC_FACE_ALIGNMENT\x10\xc9\x01\x12\x1d\n\x18RECFUNC_FACE_QUALITY_LV1\x10\xca\x01\x12\x1d\n\x18RECFUNC_FACE_QUALITY_LV2\x10\xcb\x01\x12\x19\n\x14RECFUNC_FACE_FEATURE\x10\xcc\x01\x12\x1b\n\x16RECFUNC_FACE_ATTRIBUTE\x10\xcd\x01\x12!\n\x1cRECFUNC_PEDESTRIAN_ATTRIBUTE\x10\xac\x02\x12\x1f\n\x1aRECFUNC_PEDESTRIAN_FEATURE\x10\xad\x02\x12 \n\x1bRECFUNC_NON_MOTOR_ATTRIBUTE\x10\x90\x03\x12\x1e\n\x19RECFUNC_NON_MOTOR_FEATURE\x10\x91\x03\x12$\n\x1fRECFUNC_NON_MOTOR_LICENSE_PLATE\x10\x92\x03\x62\x06proto3')
)

_RECOGNIZETYPE = _descriptor.EnumDescriptor(
  name='RecognizeType',
  full_name='dg.model.RecognizeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REC_TYPE_INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REC_TYPE_VEHICLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REC_TYPE_FACE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REC_TYPE_ALL', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=120,
  serialized_end=216,
)
_sym_db.RegisterEnumDescriptor(_RECOGNIZETYPE)

RecognizeType = enum_type_wrapper.EnumTypeWrapper(_RECOGNIZETYPE)
_RANKTYPE = _descriptor.EnumDescriptor(
  name='RankType',
  full_name='dg.model.RankType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RANK_TYPE_DEFAULT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANK_TYPE_VEHICLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANK_TYPE_FACE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=218,
  serialized_end=294,
)
_sym_db.RegisterEnumDescriptor(_RANKTYPE)

RankType = enum_type_wrapper.EnumTypeWrapper(_RANKTYPE)
_RECOGNIZEFUNCTIONS = _descriptor.EnumDescriptor(
  name='RecognizeFunctions',
  full_name='dg.model.RecognizeFunctions',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_VEHICLE_DETECT', index=1, number=100,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_MOTOR_STYLE', index=2, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_MOTOR_COLOR', index=3, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_MOTOR_MARKER', index=4, number=103,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_MOTOR_PLATE', index=5, number=104,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_MOTOR_FEATURE', index=6, number=105,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_MOTOR_DRIVER_BELT', index=7, number=106,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_MOTOR_DRIVER_PHONE', index=8, number=107,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_MOTOR_CODRIVER_BELT', index=9, number=108,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_MOTOR_DANGEROUS_ARTICLES_DETECT', index=10, number=109,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_MOTOR_HEAVY_POLLUTION_DETECT', index=11, number=110,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_MOTOR_MUCK_DETECT', index=12, number=111,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_MOTOR_FACECOVER_DETECT', index=13, number=112,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_FACE_DETECT', index=14, number=200,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_FACE_ALIGNMENT', index=15, number=201,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_FACE_QUALITY_LV1', index=16, number=202,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_FACE_QUALITY_LV2', index=17, number=203,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_FACE_FEATURE', index=18, number=204,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_FACE_ATTRIBUTE', index=19, number=205,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_PEDESTRIAN_ATTRIBUTE', index=20, number=300,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_PEDESTRIAN_FEATURE', index=21, number=301,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_NON_MOTOR_ATTRIBUTE', index=22, number=400,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_NON_MOTOR_FEATURE', index=23, number=401,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECFUNC_NON_MOTOR_LICENSE_PLATE', index=24, number=402,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=297,
  serialized_end=1089,
)
_sym_db.RegisterEnumDescriptor(_RECOGNIZEFUNCTIONS)

RecognizeFunctions = enum_type_wrapper.EnumTypeWrapper(_RECOGNIZEFUNCTIONS)
REC_TYPE_INVALID = 0
REC_TYPE_VEHICLE = 1
REC_TYPE_FACE = 2
REC_TYPE_ALL = 3
RANK_TYPE_DEFAULT = 0
RANK_TYPE_VEHICLE = 1
RANK_TYPE_FACE = 2
RECFUNC_INVALID = 0
RECFUNC_VEHICLE_DETECT = 100
RECFUNC_MOTOR_STYLE = 101
RECFUNC_MOTOR_COLOR = 102
RECFUNC_MOTOR_MARKER = 103
RECFUNC_MOTOR_PLATE = 104
RECFUNC_MOTOR_FEATURE = 105
RECFUNC_MOTOR_DRIVER_BELT = 106
RECFUNC_MOTOR_DRIVER_PHONE = 107
RECFUNC_MOTOR_CODRIVER_BELT = 108
RECFUNC_MOTOR_DANGEROUS_ARTICLES_DETECT = 109
RECFUNC_MOTOR_HEAVY_POLLUTION_DETECT = 110
RECFUNC_MOTOR_MUCK_DETECT = 111
RECFUNC_MOTOR_FACECOVER_DETECT = 112
RECFUNC_FACE_DETECT = 200
RECFUNC_FACE_ALIGNMENT = 201
RECFUNC_FACE_QUALITY_LV1 = 202
RECFUNC_FACE_QUALITY_LV2 = 203
RECFUNC_FACE_FEATURE = 204
RECFUNC_FACE_ATTRIBUTE = 205
RECFUNC_PEDESTRIAN_ATTRIBUTE = 300
RECFUNC_PEDESTRIAN_FEATURE = 301
RECFUNC_NON_MOTOR_ATTRIBUTE = 400
RECFUNC_NON_MOTOR_FEATURE = 401
RECFUNC_NON_MOTOR_LICENSE_PLATE = 402



_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='dg.model.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Seconds', full_name='dg.model.Time.Seconds', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NanoSecs', full_name='dg.model.Time.NanoSecs', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=72,
)


_MATRIXERROR = _descriptor.Descriptor(
  name='MatrixError',
  full_name='dg.model.MatrixError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Code', full_name='dg.model.MatrixError.Code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Message', full_name='dg.model.MatrixError.Message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['Time'] = _TIME
DESCRIPTOR.message_types_by_name['MatrixError'] = _MATRIXERROR
DESCRIPTOR.enum_types_by_name['RecognizeType'] = _RECOGNIZETYPE
DESCRIPTOR.enum_types_by_name['RankType'] = _RANKTYPE
DESCRIPTOR.enum_types_by_name['RecognizeFunctions'] = _RECOGNIZEFUNCTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), dict(
  DESCRIPTOR = _TIME,
  __module__ = 'localcommon_pb2'
  # @@protoc_insertion_point(class_scope:dg.model.Time)
  ))
_sym_db.RegisterMessage(Time)

MatrixError = _reflection.GeneratedProtocolMessageType('MatrixError', (_message.Message,), dict(
  DESCRIPTOR = _MATRIXERROR,
  __module__ = 'localcommon_pb2'
  # @@protoc_insertion_point(class_scope:dg.model.MatrixError)
  ))
_sym_db.RegisterMessage(MatrixError)


# @@protoc_insertion_point(module_scope)
